### ISSUE TITLE
PushButton enable / disable problems...

### ISSUE THREAD

**Issue by mcolliver** [lawsie/guizero#83]
Seem to be having issues with working with the enable/disable methods of PushButton.

If I set a PushButton to be disabled - I seem to still be able to click it?

Also I would like to be able to toggle a button (but this does not seem to work if included inside the 'command')

So imagine two buttons, a START and a STOP.
STOP button is initially disabled.

The 'command' for the START button toggles both buttons. The START button does not disable but the STOP button will enable.

Code that seems to allow me to click on a disabled button (unless I'm not understanding something):

```
from guizero import App, PushButton
def do_nothing():
  print("Button was pressed")
  button.toggle()

app = App()
button = PushButton(app, command=do_nothing)
button.disable()
app.display()
```

Two button toggle code:

```
from guizero import App, PushButton
def do_start():
  print("Start button was pressed")
  startbutton.toggle()
  stopbutton.toggle()

def do_stop():
  print("Stop button was pressed")
  startbutton.toggle()
  stopbutton.toggle()
  

app = App()
startbutton = PushButton(app, command=do_start, text='Start')
stopbutton = PushButton(app, command=do_stop, text='Stop')
stopbutton.disable()
app.display()

```

**Comment by martinohanlon** [comment]
Thanks for raising an issue. Some brief investigation suggests you have found 2 bugs in PushButton:
 - _on_release() should not call _command() if the state is disabled
 - toggle() only checks for "normal" and "disable" states, if the state is "active", which it is when the button has been 'pressed' it doesn't toggle to "disable"

I'll include fixes in the next release.

Also noticed that change_command() works but not as intended it should update the internal self._command not the tk command.

**Comment by martinohanlon** [comment]
Fixed in dev - it will go into release 0.4.1

[commit 1](https://github.com/lawsie/guizero/commit/81e5edd19d0d230a05918c21f234cbfed3bfc8d2)
[commit 2](https://github.com/lawsie/guizero/commit/dc09f35d25352332a3e4f2e2fde17e321c6f5f7e)

**Comment by martinohanlon** [comment]
in version 0.4.1 just released.

**Comment by mcolliver** [comment]
Thanks - this has fixed the previous ability to click a disable PushButton.

The 'toggle_state' example still appears to not work in the way I would hope.
Whilst you can toggle / change the state of another button - it seems that you can't change the state of the button clicked. So click on the START button and the STOP button will enable - but the START button will not disable... (hunting through the code for any sign of a bug)

**Comment by mcolliver** [comment]
Interestingly the START button does think that the property enabled is False once it is clicked - but it still displays as enabled.

```
from guizero import App, PushButton
def do_start():
    print("Start button was pressed")
    startbutton.disable()
    stopbutton.enable()
    print(startbutton.enabled)

def do_stop():
    print("Stop button was pressed")
    startbutton.toggle()
    stopbutton.toggle()

app = App()
startbutton = PushButton(app, command=do_start, text='Start')
stopbutton = PushButton(app, command=do_stop, text='Stop')
stopbutton.disable()
app.display()
```

**Comment by mcolliver** [comment]
This code has the 'enabled' property working correctly but the buttons don't display properly:

```
from guizero import App, PushButton
def do_start():
    print("Start button was pressed")
    startbutton.disable()
    stopbutton.enable()
    print('Start state is',startbutton.enabled)
    print('Stop sate is',stopbutton.enabled)

def do_stop():
    print("Stop button was pressed")
    startbutton.enable()
    stopbutton.disable()
    print('Start state is',startbutton.enabled)
    print('Stop sate is',stopbutton.enabled)

app = App()
startbutton = PushButton(app, command=do_start, text='Start')
stopbutton = PushButton(app, command=do_stop, text='Stop')
stopbutton.disable()
app.display()
```

**Comment by martinohanlon** [comment]
When you say "button dont display properly" do you mean that they arent 'greyed out' when they are disabled?

If so, I dont experience this behaviour. 

Using your program above - when it first runs the Start button text is Black and the Stop button text is grey

![but1](https://user-images.githubusercontent.com/2329501/34431864-97c97c32-ec6a-11e7-9e48-93b0e9b6ee9b.PNG)

When I click Start, the Stop button goes black and the Start grey

![but2](https://user-images.githubusercontent.com/2329501/34431865-97e37524-ec6a-11e7-9422-42520385a3df.PNG)

When I click Stop, Start is black, Stop is grey

![but3](https://user-images.githubusercontent.com/2329501/34431866-97fb207a-ec6a-11e7-927e-68aef7af4732.PNG)

I wondered if this was a platform problem, but I have tested on Windows, Linux and Pi - I cant test on Mac right now though.

**Comment by mcolliver** [comment]
Must be a platform problem then - was testing on my Mac and didn't get round to testing on a Pi.
Thanks for looking at this.
